apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-03-27T13:50:12Z"
  labels:
    name: app
  name: app
  namespace: elastic-stack
  resourceVersion: "620"
  uid: e66dec13-007e-4515-9df9-c32afb71ec75
spec:
  containers:
    - image: kodekloud/event-simulator
      imagePullPolicy: Always
      name: app
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /log
          name: log-volume
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-wk9zj
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - hostPath:
        path: /var/log/webapp
        type: DirectoryOrCreate
      name: log-volume
    - name: kube-api-access-wk9zj
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-03-27T13:50:18Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2024-03-27T13:50:12Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-03-27T13:50:18Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-03-27T13:50:18Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-03-27T13:50:12Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: containerd://b02176861137049e6720c7287a8177fec60296f1e485746659df89e2df8377fb
      image: docker.io/kodekloud/event-simulator:latest
      imageID: docker.io/kodekloud/event-simulator@sha256:1e3e9c72136bbc76c96dd98f29c04f298c3ae241c7d44e2bf70bcc209b030bf9
      lastState: {}
      name: app
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-03-27T13:50:18Z"
  hostIP: 192.30.183.3
  hostIPs:
    - ip: 192.30.183.3
  phase: Running
  podIP: 10.244.0.4
  podIPs:
    - ip: 10.244.0.4
  qosClass: BestEffort
  startTime: "2024-03-27T13:50:12Z"