apiVersion: v1
kind: Pod
metadata:
  name: yellow
spec:
  containers:
    - name: lemon
      image: busybox
      command: ["sh", "-c", "while true; do echo 'Lemon Container is running...'; sleep 10; done"]
      # If the pod goes into the crashloopbackoff, add the command sleep 1000 in the lemon container
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "if [ ! -f /tmp/initialized ]; then sleep 1000; touch /tmp/initialized; fi"]
      volumeMounts:
        - name: shared-data
          mountPath: /tmp
    - name: gold
      image: redis
      command: ["redis-server"]
  volumes:
    - name: shared-data
      emptyDir: {}
