apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-deployment
  namespace: default
spec:
  clusterIP: 10.43.216.1
  clusterIPs:
    - 10.43.216.1
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32302
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: simple-webapp
  sessionAffinity: None
  type: NodePort
