apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
spec:
  ports:
    - nodePort:
      port: 8080
      targetPort: 8080
  selector:
    name: simple-webapp
  type: NodePort