apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nova
  name: nova
  namespace: default
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - echo "Custom script executed"; sleep 3600
      env:
        - name: APP_ENV
          value: production
      image: nginx
      name: nova
      ports:
        - containerPort: 8080
          protocol: TCP
