apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: main-app
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: sidecar
      image: busybox:latest
      ports:
        - containerPort: 8080
      command: ["sleep", "3600"]
