apiVersion: v1
kind: Pod
metadata:
  labels:
    app: vega
  name: vega
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - echo "Custom script executed"; sleep 3600
      env:
        - name: ENV
          value: PROD
      image: nginx
      name: vega
      ports:
        - containerPort: 8080
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
