apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: #####
    server: https://k8scp:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:node:ip-172-31-40-74
  name: system:node:ip-172-31-40-74@kubernetes
current-context: system:node:ip-172-31-40-74@kubernetes
kind: Config
users:
- name: system:node:ip-172-31-40-74
  user:
    client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
    client-key: /var/lib/kubelet/pki/kubelet-client-current.pem
