apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  securityContext:
    runAsUser: 1010
  containers:
    - command:
        - sleep
        - "4800"
      image: ubuntu
      name: ubuntu-sleeper

#To delete the existing ubuntu-sleeper pod:
#
#  kubectl delete po ubuntu-sleeper
#After that apply solution manifest file to run as user 1010 as follows:

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: ubuntu-sleeper
#  namespace: default
#spec:
#  securityContext:
#    runAsUser: 1010
#  containers:
#    - command:
#        - sleep
#        - "4800"
#      image: ubuntu
#      name: ubuntu-sleeper

#Then run the command kubectl apply -f <file-name>.yaml to create a resource.
#
#NOTE: TO delete the pod faster, you can run kubectl delete pod ubuntu-sleeper --force. This can be done for any pod in the lab or the actual exam. It is not recommended to run this in Production, so keep a note of that.