#                   StorageClass

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: delayed-volume-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
    - image: nginx:alpine
      name: nginx
      volumeMounts:
        - name: local-persistent-storage
          mountPath: /var/www/html

  dnsPolicy: ClusterFirst
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: local-pvc
  restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-storage
  resources:
    requests:
      storage: 500Mi

---



apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 50Mi



#  after delteing the pvc the pvc hangs in terminating
#  deleting the pod the pvc is deleted the pv is released but not available
#
#  dynamic volume provisioning

