apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: andromeda
spec:
  rules:
    - host: awsprolearner.link
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
