apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  namespace: auth
spec:
  containers:
    - name: my-busybox
      image: busybox
      command: ['sh', '-c', 'while true; do echo success > /output/output.log; sleep 5; done']
      volumeMounts:
        - mountPath: "/out"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: host-storage-pv