apiVersion: v1
kind: Service
metadata:
  labels:
    app: andromeda
  name: andromeda-cluster-ip
  namespace: default
spec:
  clusterIP: 10.106.99.246
  clusterIPs:
    - 10.106.99.246
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: andromeda
  sessionAffinity: None
  type: ClusterIP
