apiVersion: v1
kind: Service
metadata:
  labels:
    app: andromeda
  name: andromeda-load-balancer
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.78.195
  clusterIPs:
    - 10.98.78.195
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32064
  selector:
    app: andromeda
  sessionAffinity: None
  type: LoadBalancer
