apiVersion: v1
kind: Service
metadata:
  labels:
    app: andromeda
  name: andromeda-node-port
  namespace: default
spec:
  clusterIP: 10.96.162.69
  clusterIPs:
    - 10.96.162.69
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31241
  selector:
    app: andromeda
  sessionAffinity: None
  type: NodePort
